[[whatsNew]]
= What's new in Spring Batch 6.1

This section highlights the major changes in Spring Batch 6.1. For the complete list of changes, please refer to the https://github.com/spring-projects/spring-batch/releases[release notes].

Spring Batch 6.1 includes the following features and improvements:

* xref:whatsnew.adoc#dependencies-upgrade[Dependencies upgrade]
* xref:whatsnew.adoc#collection-prefix-for-the-mongodb-job-repository[Collection prefix for the MongoDB job repository]
* xref:whatsnew.adoc#deprecations[Deprecations]

[[dependencies-upgrade]]
== Dependencies upgrade

In this release, Spring dependencies are upgraded to the following versions:

* Spring Framework 7.1
* Spring Integration 7.2
* Spring Data 2026.1.0
* Spring LDAP 4.1
* Spring AMQP 4.2
* Spring Kafka 4.2
* Micrometer 1.18

[[collection-prefix-for-the-mongodb-job-repository]]
== Collection prefix for the MongoDB job repository

The MongoDB job repository now supports a configurable collection prefix, similar to the
table prefix of the JDBC job repository. This makes it possible to run several
applications against the same MongoDB database, or to isolate environments from each
other:

[source, java]
----
@EnableBatchProcessing
@EnableMongoJobRepository(collectionPrefix = "MY_APP_")
class MyJobConfiguration {

	// job definition omitted

}
----

The prefix defaults to `BATCH_`, so existing applications are not affected. For more
details, please refer to the
xref:job/configuring-repository.adoc#repositoryCollectionPrefix[Changing the Collection Prefix]
section.

[[deprecations]]
== Deprecations

The following features have been deprecated in Spring Batch 6.1:

* Deprecate Apache Derby support (`DatabaseType.DERBY`, `DerbyPagingQueryProvider` and the Derby DDL scripts), scheduled for removal in version 7.0.0
